(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require map.Map.

Axiom array : forall (a:Type), Type.
Parameter array_WhyType :
  forall (a:Type) {a_WT:WhyType a}, WhyType (array a).
Existing Instance array_WhyType.

Parameter elts:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z -> a.

Parameter length:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z.

Axiom array'invariant :
  forall {a:Type} {a_WT:WhyType a},
  forall (self:array a), (0%Z <= (length self))%Z.

(* Why3 assumption *)
Definition mixfix_lbrb {a:Type} {a_WT:WhyType a} (a1:array a)
    (i:Numbers.BinNums.Z) : a :=
  elts a1 i.

Parameter mixfix_lblsmnrb:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z -> a ->
  array a.

Axiom mixfix_lblsmnrb'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:array a) (i:Numbers.BinNums.Z) (v:a),
  ((length (mixfix_lblsmnrb a1 i v)) = (length a1)) /\
  ((elts (mixfix_lblsmnrb a1 i v)) = (map.Map.set (elts a1) i v)).

Parameter make:
  forall {a:Type} {a_WT:WhyType a}, Numbers.BinNums.Z -> a -> array a.

Axiom make'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (n:Numbers.BinNums.Z) (v:a), (0%Z <= n)%Z ->
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z /\ (i < n)%Z ->
   ((mixfix_lbrb (make n v) i) = v)) /\
  ((length (make n v)) = n).

Parameter us_FORMULA_TO_BE_COMPLETED__: Prop.

Parameter us_TERM_TO_BE_COMPLETED__: forall {a:Type} {a_WT:WhyType a}, a.

Parameter us_VARIANT_TO_BE_COMPLETED__: Numbers.BinNums.Z.

(* Why3 assumption *)
Inductive elem :=
  | Zero : elem
  | One : elem
  | Empty : elem.
Axiom elem_WhyType : WhyType elem.
Existing Instance elem_WhyType.

(* Why3 assumption *)
Definition takuzu_grid := array elem.

(* Why3 assumption *)
Definition row_start_index (n:Numbers.BinNums.Z) : Numbers.BinNums.Z :=
  (8%Z * (ZArith.BinInt.Z.quot n 8%Z))%Z.

(* Why3 assumption *)
Definition valid_chunk (s:Numbers.BinNums.Z) (i:Numbers.BinNums.Z) : Prop :=
  (i = 1%Z) /\
  ((0%Z <= s)%Z /\ (s <= 56%Z)%Z) /\ ((ZArith.BinInt.Z.rem s 8%Z) = 0%Z) \/
  (i = 8%Z) /\ (0%Z <= s)%Z /\ (s <= 7%Z)%Z.

Axiom valid_chunk1 :
  forall (s:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), valid_chunk s i ->
  forall (k:Numbers.BinNums.Z), (0%Z <= k)%Z /\ (k < 8%Z)%Z ->
  (0%Z <= (s + (k * i)%Z)%Z)%Z /\ ((s + (k * i)%Z)%Z < 64%Z)%Z.

(* Why3 assumption *)
Definition acc (g:array elem) (start:Numbers.BinNums.Z)
    (incr:Numbers.BinNums.Z) (k:Numbers.BinNums.Z) : elem :=
  mixfix_lbrb g (start + (incr * k)%Z)%Z.

(* Why3 assumption *)
Definition no_3_consecutive_identical_elem (g:array elem)
    (start:Numbers.BinNums.Z) (incr:Numbers.BinNums.Z)
    (l:Numbers.BinNums.Z) : Prop :=
  forall (k:Numbers.BinNums.Z), (0%Z <= k)%Z /\ (k < (l - 2%Z)%Z)%Z ->
  let acc1 :=
  (fun (y0:array elem) (y1:Numbers.BinNums.Z) (y2:Numbers.BinNums.Z)
   (y3:Numbers.BinNums.Z) => acc y0 y1 y2 y3)
  g start incr in
  ~ (((acc1 k) = (acc1 (k + 1%Z)%Z)) /\
     ((acc1 (k + 1%Z)%Z) = (acc1 (k + 2%Z)%Z)) /\ ((acc1 (k + 2%Z)%Z) = Zero)) /\
  ~ (((acc1 k) = (acc1 (k + 1%Z)%Z)) /\
     ((acc1 (k + 1%Z)%Z) = (acc1 (k + 2%Z)%Z)) /\ ((acc1 (k + 2%Z)%Z) = One)).

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

Parameter num_occ:
  elem -> array elem -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom num_occ'def :
  forall (e:elem) (g:array elem) (start:Numbers.BinNums.Z)
    (incr:Numbers.BinNums.Z) (l:Numbers.BinNums.Z),
  ((length g) = 64%Z) -> valid_chunk start incr ->
  (0%Z <= l)%Z /\ (l <= 8%Z)%Z ->
  ((l = 0%Z) -> ((num_occ e g start incr l) = 0%Z)) /\
  (~ (l = 0%Z) ->
   (((acc g start incr (l - 1%Z)%Z) = e) ->
    ((num_occ e g start incr l) =
     (1%Z + (num_occ e g start incr (l - 1%Z)%Z))%Z)) /\
   (~ ((acc g start incr (l - 1%Z)%Z) = e) ->
    ((num_occ e g start incr l) = (num_occ e g start incr (l - 1%Z)%Z)))).

(* Why3 assumption *)
Definition rule_2_for_chunk (g:array elem) (start:Numbers.BinNums.Z)
    (incr:Numbers.BinNums.Z) : Prop :=
  ((num_occ Zero g start incr 8%Z) <= 4%Z)%Z /\
  ((num_occ One g start incr 8%Z) <= 4%Z)%Z.

(* Why3 assumption *)
Definition identical_chunks (g:array elem) (s1:Numbers.BinNums.Z)
    (s2:Numbers.BinNums.Z) (incr:Numbers.BinNums.Z) (l:Numbers.BinNums.Z) :
    Prop :=
  forall (k:Numbers.BinNums.Z), (0%Z <= k)%Z /\ (k < l)%Z ->
  ((acc g s1 incr k) = (acc g s2 incr k)) /\ ~ ((acc g s1 incr k) = Empty).

(* Why3 assumption *)
Definition rule_1_for_cell (g:array elem) (n:Numbers.BinNums.Z) : Prop :=
  no_3_consecutive_identical_elem g (row_start_index n) 1%Z 8%Z /\
  no_3_consecutive_identical_elem g (ZArith.BinInt.Z.rem n 8%Z) 8%Z 8%Z.

(* Why3 assumption *)
Definition rule_2_for_cell (g:array elem) (n:Numbers.BinNums.Z) : Prop :=
  rule_2_for_chunk g (row_start_index n) 1%Z /\
  rule_2_for_chunk g (ZArith.BinInt.Z.rem n 8%Z) 8%Z.

(* Why3 assumption *)
Definition rule_3_for_cell (g:array elem) (n:Numbers.BinNums.Z) : Prop :=
  let cs := ZArith.BinInt.Z.rem n 8%Z in
  let rs := row_start_index n in
  forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z /\ (i < 8%Z)%Z ->
  (~ ((i * 8%Z)%Z = rs) -> ~ identical_chunks g rs (i * 8%Z)%Z 1%Z 8%Z) /\
  (~ (i = cs) -> ~ identical_chunks g cs i 8%Z 8%Z).

(* Why3 assumption *)
Definition valid_for_cell (g:array elem) (i:Numbers.BinNums.Z) : Prop :=
  rule_1_for_cell g i /\ rule_2_for_cell g i /\ rule_3_for_cell g i.

(* Why3 assumption *)
Definition valid_up_to (g:array elem) (n:Numbers.BinNums.Z) : Prop :=
  forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z /\ (i < n)%Z ->
  valid_for_cell g i.

(* Why3 assumption *)
Definition map_eq_sub {a:Type} {a_WT:WhyType a} (a1:Numbers.BinNums.Z -> a)
    (a2:Numbers.BinNums.Z -> a) (l:Numbers.BinNums.Z) (u:Numbers.BinNums.Z) :
    Prop :=
  forall (i:Numbers.BinNums.Z), (l <= i)%Z /\ (i < u)%Z -> ((a1 i) = (a2 i)).

(* Why3 assumption *)
Definition array_eq_sub {a:Type} {a_WT:WhyType a} (a1:array a) (a2:array a)
    (l:Numbers.BinNums.Z) (u:Numbers.BinNums.Z) : Prop :=
  ((length a1) = (length a2)) /\
  ((0%Z <= l)%Z /\ (l <= (length a1))%Z) /\
  ((0%Z <= u)%Z /\ (u <= (length a1))%Z) /\
  map_eq_sub (elts a1) (elts a2) l u.

(* Why3 assumption *)
Definition array_eq {a:Type} {a_WT:WhyType a} (a1:array a) (a2:array a) :
    Prop :=
  ((length a1) = (length a2)) /\
  map_eq_sub (elts a1) (elts a2) 0%Z (length a1).

Axiom equal_up_to_refl :
  forall {a:Type} {a_WT:WhyType a},
  forall (g:array a) (n:Numbers.BinNums.Z),
  (0%Z <= n)%Z /\ (n < (length g))%Z -> array_eq_sub g g 0%Z n.

Axiom equal_up_to_useless_mod' :
  forall (g1:array elem) (g2:array elem) (e:elem) (n:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z),
  (0%Z <= m)%Z /\ (m < (length g1))%Z -> (0%Z <= n)%Z /\ (n <= m)%Z ->
  array_eq_sub g1 g2 0%Z n <-> array_eq_sub g1 (mixfix_lblsmnrb g2 m e) 0%Z n.

Axiom equal_up_to_useless_mod :
  forall (g:array elem) (e:elem) (n:Numbers.BinNums.Z) (m:Numbers.BinNums.Z),
  (0%Z <= m)%Z /\ (m < (length g))%Z -> (0%Z <= n)%Z /\ (n <= m)%Z ->
  array_eq_sub g (mixfix_lblsmnrb g m e) 0%Z n.

Axiom valid_up_to_morphism :
  forall (g1:array elem) (g2:array elem) (n:Numbers.BinNums.Z),
  array_eq_sub g1 g2 0%Z n -> valid_up_to g1 n <-> valid_up_to g2 n.

Axiom valid_up_to_useless_mod :
  forall (g:array elem) (e:elem) (n:Numbers.BinNums.Z) (m:Numbers.BinNums.Z),
  (0%Z <= m)%Z /\ (m < (length g))%Z -> (0%Z <= n)%Z /\ (n <= m)%Z ->
  valid_up_to g n <-> valid_up_to (mixfix_lblsmnrb g m e) n.

Axiom valid_up_to_extend :
  forall (g:array elem) (e:elem) (n:Numbers.BinNums.Z), valid_up_to g n ->
  valid_for_cell (mixfix_lblsmnrb g n e) n ->
  valid_up_to (mixfix_lblsmnrb g n e) (n + 1%Z)%Z.

(* Why3 assumption *)
Definition full_up_to (g:array elem) (n:Numbers.BinNums.Z) : Prop :=
  forall (k:Numbers.BinNums.Z), (0%Z <= k)%Z /\ (k < n)%Z ->
  ~ ((mixfix_lbrb g k) = Empty).

(* Why3 assumption *)
Definition extends (g1:array elem) (g2:array elem) : Prop :=
  forall (k:Numbers.BinNums.Z), (0%Z <= k)%Z /\ (k < 64%Z)%Z ->
  ~ ((mixfix_lbrb g1 k) = Empty) -> ((mixfix_lbrb g2 k) = (mixfix_lbrb g1 k)).

Axiom full_up_to_morphism :
  forall (g1:array elem) (g2:array elem) (n:Numbers.BinNums.Z),
  array_eq_sub g1 g2 0%Z n -> full_up_to g1 n -> full_up_to g2 n.

Axiom full_up_to_less :
  forall (g:array elem) (n:Numbers.BinNums.Z), full_up_to g (n + 1%Z)%Z ->
  full_up_to g n.

Require Import Lia.

(* Why3 goal *)
Theorem valid_up_to_less :
  forall (g:array elem) (n:Numbers.BinNums.Z), valid_up_to g (n + 1%Z)%Z ->
  valid_up_to g n.
(* Why3 intros g n h1. *)
Proof.
  intros g n h1 i H.
  apply h1.
  lia.
Qed.

